# Jason Downing
# Assignment 4
# Operating Systems - COMP.3080
# 11/8/2016
#
# Makefile for Assignment 4
# File given by Prof. Moloney at the following URL:
# http://www.cs.uml.edu/~bill/cs308/assignment_3_makefile.txt
#
# I modified it for Assignment 4.
#
# This line is from Moloney's help file from the following URL:
# http://www.cs.uml.edu/~bill/cs308/call_help_assign4.txt
#
# gcc -o my_th_donuts my_th_donuts.c -lpthread

pc_threads: pc_threads.h pc_threads.c
	gcc -o pc_threads pc_threads.c -lpthread

clean:
	rm *.o pc_threads c*
