# Standard flags for compiling C programs.
CC = gcc

all:
	# Compile the two programs.
	$(CC) a2_sort.c -o a2_sort
	$(CC) a2_grep.c -o a2_grep

clean:
	# Remove the executable / output file.
	rm a2_sort a2_grep sorted_data
