# Jason Downing
# Makefile for Assignment #3
# 10/6/2016
CC = gcc
FLAGS = -O -Werror -Wall -Wextra -Wundef -Winit-self

all: a3

a3:	a3.c
	$(CC) a3.c $(FLAGS) -o a3

clean:
	# Remove the executable / output file.
	rm a3
