# Jason Downing
# Makefile for Assignment #3
# 10/24/2016
CC = gcc

# Make everything
all: consdonuts proddonuts

# Make producer code
proddonuts: donuts.h proddonuts.o utilities.o
	$(CC) -o proddonuts proddonuts.o utilities.o

# Make consumer code
consdonuts: donuts.h consdonuts.o utilities.o
	$(CC) -o consdonuts consdonuts.o utilities.o

# Consumer object file
consdonuts.o: donuts.h consdonuts.c
	$(CC) -c consdonuts.c

# Producer object file
proddonuts.o: donuts.h proddonuts.c
	$(CC) -c proddonuts.c

# Utilities object file
utilities.o:  utilities.c
	$(CC) -c utilities.c

# Cleanup everything
clean:
	rm *.o proddonuts consdonuts
