# Standard flags for compiling C programs.
CC = gcc
#CFLAGS	= -std=c99 -o -Werror -Wextra -Wall

all:
	# Compile the program.
	$(CC) $(CFLAGS) a1.c -o a1

	# Compile the professor's program.
	$(CC) $(CFLAGS) assign1.c -o assign1

clean:
	# Remove the executable / output file.
	rm a1
