# Standard flags for compiling C programs.
CC = gcc

all:
	# Compile the program.
	$(CC) a1.c -o a1

	# Compile the professor's program.
	$(CC) assign1.c -o assign1

clean:
	# Remove the executable / output file.
	rm a1 assign1
