# Jason Downing
# Assignment 5
# Operating Systems - COMP.3080
# 11/29/2016
#
# Makefile for Assignment 5
# File given by Prof. Moloney at the following URL:
# http://www.cs.uml.edu/~bill/cs308/assignment_3_makefile.txt
#
# I modified it for Assignment 5.
#

pc_threads: pc_threads.h pc_threads.c
	gcc -o pc_threads pc_threads.c -lpthread

clean:
	rm *.o pc_threads c*
